### ISSUE TITLE
Yarn Node-SASS

### ISSUE THREAD

**Issue by Abdulla-Shahid** [GTHC/web#38]
Using a package but having a problem with the Node Version (need 8, current node-v = 10). Tried downgrading to Node 8 but I think node-v of docker has to change maybe. To get the issue, go to index.jsx file, and comment out the two import lines regarding "fancy-countdown" and the fancy countdown component in the grid (underneath "hi"). 
Only happening in Abdulla-CDWidget branch 
To get the issue, uncomment the above lines, and run the program 
Have gotten different kinds of error messages either Node-SASS related or Node-V related. Screenshots belwo

![image](https://user-images.githubusercontent.com/22209648/50379324-4698a700-0615-11e9-9651-cc66a92053a4.png)
or something along the lines of Node-V is 10 for Linux-x and needs to be node-8.x (don't have SC)

**Comment by amanmibra** [comment]
We should never, _ever_ have to depreciate/downgrade any of our main services such node or ruby. The only exception is if it is external library where it is possible an earlier version functions better as the latest is under beta. If anything this raises red flags for the library.

The library you are using is pretty obscure, if you go to the libraries page you see only 10 downloads and there are no stars or issues on the github page except from the developer them self which shows it is clearly an independent project of some sort and not meant for our use case.

You should just use the one that I recommended to you earlier: 

https://www.npmjs.com/package/react-countdown-now

This has 10,000+ downloads, whereas, the other only has <10, which is night and day in terms of updates, accommodating to different environments, community involvement, etc. Please look for these sort of things before you start adding/downloading dependencies as we try to make sure we add the least amount of dependencies as possible and also let's avoid using unreliable libraries such as this one as if something breaks and there is no one to fix it on their end, then that hurts us.

#### What to do now
I would just go ahead and use `react-countdown-now` instead of `react-fancy-countdown`, and I would scrap this branch in its entirety and make a new one and install and implement the new library. (Also, for the branch naming scheme lets stay consistent and use lowercase only, and name it something like `countdown-widget`. This is so we can follow industry convention rather than have some jumbled mess. If you have time, I would even look at this which shows git conventions in general and not just for branch names, but also for how you should commit, merge, and etc.)

https://github.com/agis/git-style-guide
